name: ItemMail
main: taco.im.ItemMail
version: 2.01.09
description: Easily send items to players
commands:
  itemmail:
    usage: /itemmail [send/read]
    description: ItemMail commands
    aliases: im